[package]
name = "sidekiq-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "*"
tokio = { version = "1", features = ["full"]} 
serde_json = { version = "1" }
serde = { version = "1.0", features = ["derive"] }
redis = { version = "*", features = ["r2d2", "aio", "default", "tokio-comp"] }
async-trait = "*"
slog = "*"
slog-term = "*"
dyn-clone = "*"
bb8-redis = "*"
